adminPages:
    pattern:  /
    defaults: { _controller: "MyappadminBundle:PagesAdmin:index1" }
admin_users_lock_page:
    path:     /lock/{id}
    defaults: { _controller: MyappadminBundle:client:lock }    

adminPages_show:
    pattern:  /{id}/show
    defaults: { _controller: "MyappadminBundle:PagesAdmin:show" }

adminPages_new:
    pattern:  /new
    defaults: { _controller: "MyappadminBundle:PagesAdmin:new" }

adminPages_create:
    pattern:  create
    defaults: { _controller: "MyappadminBundle:PagesAdmin:create" }
   

adminPages_edit:
    pattern:  /edit
    defaults: { _controller: "MyappadminBundle:PagesAdmin:edit" }

adminPages_update:
    pattern:  /{id}/update
    defaults: { _controller: "MyappadminBundle:PagesAdmin:update" }
   

adminPages_delete:
    pattern:  /1/delete
    defaults: { _controller: "MyappadminBundle:PagesAdmin:delete" }


affich:
    pattern:  /affichage
    defaults: { _controller: "MyappadminBundle:client:list" }
    
aaa:
    path:     /supprimer/{id}
    defaults: { _controller: "MyappadminBundle:client:supprimer" }     
rech:
    path:     /rech
    defaults: { _controller: "MyappadminBundle:client:Recherche" } 
profile:
    path:     /profile
    defaults: { _controller: "MyappadminBundle:Profile2:show" }
edit1:
    path:     /edit
    defaults: { _controller: "MyappadminBundle:Profile2:edit" }  
#changePassword:
#    path:     /changePassword
#    defaults: { _controller: "MyappadminBundle:ChangePassword:changePassword" }    
logout:
    path:     /logout
    defaults: { _controller: "MyappadminBundle:Security:logout" }    
upload_pack: 
    path: /upload 
    defaults: { _controller: MyappadminBundle:Image:upload } 
    
graphe_homepage:
    path:     /hello/{name}
    defaults: { _controller: MyappadminBundle:Default:index }
_grapheChartLine:
    path:     /ChartLine
    defaults: { _controller: MyappadminBundle:Graphe:ChartLine }  
_grapheHistogramme:
    path:     /histogramme
    defaults: { _controller: MyappadminBundle:Graphe:chartHistogramme }
_graphePie:
    path:     /pie
    defaults: { _controller: MyappadminBundle:Graphe:Pie }    
insert_pack: 
    path: /insert
    defaults: { _controller: MyappadminBundle:Img:upload }   
image_edit:
    path:     /{id}/editpa
    defaults: { _controller: MyappadminBundle:Image:edit }
affpack:
    path:     /affipack
    defaults: { _controller: "MyappadminBundle:Image:list" }  
suprimerpack:
    path:     /supprimer/{id}
    defaults: { _controller: MyappadminBundle:Image:supprimer } 
editpack:
    path:     /modifier/{id}
    defaults: { _controller: MyappadminBundle:Image:Modifier }     