myappadmin_homepage:
    path:     /hello/{name}
    defaults: { _controller: MyappadminBundle:Default:index }
PagesBundle_adminPages1:
    resource: "@MyappadminBundle/Resources/config/routingAdmin.yml"
    prefix:   /admin

page:
    pattern:  /page/{id}
    defaults: { _controller: MyappadminBundle:Pages:page }
    

