<?php

namespace Proxies\__CG__\Myapp\ResponsableBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class boutique extends \Myapp\ResponsableBundle\Entity\boutique implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = ['numero_telephone' => NULL];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->numero_telephone);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'id', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'nom', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'categorie', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'Fax', 'numero_telephone', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'Email', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'promotion', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'Description', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'etat', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'Image_cle', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'userId'];
        }

        return ['__isInitialized__', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'id', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'nom', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'categorie', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'Fax', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'Email', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'promotion', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'Description', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'etat', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'Image_cle', '' . "\0" . 'Myapp\\ResponsableBundle\\Entity\\boutique' . "\0" . 'userId'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (boutique $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->numero_telephone);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$userId]);

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', []);

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotion', []);

        return parent::getPromotion();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getImage_cle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage_cle', []);

        return parent::getImage_cle();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie($categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($Fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', [$Fax]);

        return parent::setFax($Fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($Email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$Email]);

        return parent::setEmail($Email);
    }

    /**
     * {@inheritDoc}
     */
    public function setPromotion($promotion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromotion', [$promotion]);

        return parent::setPromotion($promotion);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($Description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$Description]);

        return parent::setDescription($Description);
    }

    /**
     * {@inheritDoc}
     */
    public function setImage_cle($Image_cle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage_cle', [$Image_cle]);

        return parent::setImage_cle($Image_cle);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero_telephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero_telephone', []);

        return parent::getNumero_telephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero_telephone($numero_telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero_telephone', [$numero_telephone]);

        return parent::setNumero_telephone($numero_telephone);
    }

}
