myapp_responsable_homepage:
    path:     /hello/{name}
    defaults: { _controller: MyappResponsableBundle:Default:index }
PagesBundle_adminPages:
    resource: "@MyappResponsableBundle/Resources/config/rout/routingresponsable.yml"
    prefix:   /respensable/pages/



my_app_esprit_upload:
    path:     /upload/{id}
    defaults: { _controller: MyappResponsableBundle:Image1:upload }
my_app_esprit_list:
    path:     /list
    defaults: { _controller: MyappResponsableBundle:Image1:list }
my_app_esprit_aff_img:
   path:     /aff/{id}
   defaults: { _controller: MyappResponsableBundle:Image1:photo2 }
my_image_route:
    pattern: /images/{id}
    defaults: {_controller: MyappResponsableBundle:Image1:photo}
pi2tst_homepage1:
    path:     /homme
    defaults: { _controller: MyappResponsableBundle:Accueill:index }
registerAccount:
    path:     /register
    defaults: { _controller: MyappResponsableBundle:Accueill:register }
afficher_produits:
    path:     /afficherP
    defaults: { _controller: MyappResponsableBundle:Produit:afficherP }
paginationpa:
    path:     /hello
    defaults: { _controller: MyappResponsableBundle:Produit:afficherP2 }
afficherdetailleProduitNe :
    path:     /produit/{id}
    defaults: { _controller: MyappResponsableBundle:Produit:afficherPDetaille }
my_image_route2:
    pattern: /image/{id}
    defaults: {_controller: MyappResponsableBundle:Image1:photo2}
modifierProduit :
    pattern: /modifierProduit/{id}
    defaults: {_controller: MyappResponsableBundle:Produit:modifierProduit}
uploadAjout:
    pattern: /uploadAjout/{id}
    defaults: {_controller: MyappResponsableBundle:Image1:uploadAjout}
SupprimerProduit:
    pattern: /SupprimerProduit/{id}
    defaults: {_controller: MyappResponsableBundle:Produit:SupprimerProduit}
AjouterProduit:
    pattern: /AjouterProduit
    defaults: {_controller: MyappResponsableBundle:Produit:AjouterProduit}
uploadAjoutProduit:
    pattern: /AjouterProduitImage
    defaults: {_controller: MyappResponsableBundle:Image1:uploadAjoutProduit}
order_produit_prix_achat:
    pattern: /order_produit
    defaults: {_controller: MyappResponsableBundle:Produit:order_produit}
order_produit_prixvendre:
    pattern: /order_produit_prixvendre
    defaults: {_controller: MyappResponsableBundle:Produit:order_produit_prixvendre}
fixer_nmb_produits:
    pattern: /fixer_nmb_produits/{id}
    defaults: {_controller: MyappResponsableBundle:Produit:fixer_nmb_produits}
produit_rechercher:
    pattern: /produit_rechercher
    defaults: {_controller: MyappResponsableBundle:Produit:produit_rechercher}
afficherPClient:
    pattern: /afficherPClient
    defaults: {_controller: MyappResponsableBundle:Produit:afficherPClient}


fos_comment_api:
  type: rest

  resource: "@FOSCommentBundle/Resources/config/routing.yml"

  prefix: /api

  defaults: { _format: html }
path_categorie1:
  pattern: /cat
  defaults: { _controller: MyappResponsableBundle:boutique:list_categorie1 }
path_categorie2:
  pattern: /cat2
  defaults: { _controller: MyappResponsableBundle:boutique:list_categorie2 }
path_categorie4:
  pattern: /cat4
  defaults: { _controller: MyappResponsableBundle:boutique:list_categorie4 }
path_categorie3:
  pattern: /cat3/{nom}
  defaults: { _controller: MyappResponsableBundle:boutique:ListCategorie3 }
path_promotion:
  pattern: /promotion
  defaults: { _controller: MyappResponsableBundle:boutique:ListPromotion }
  
  
  
  
pi_homepage1:
    path:     /
    defaults: { _controller: MyappResponsableBundle:Accueill:index }
ajouterImage:
    path:     /imageAjoutF
    defaults: { _controller: MyappResponsableBundle:Produit:imageAjoutF }
afficherImage:
    path:     /afficherImage
    defaults: { _controller: MyappResponsableBundle:Produit:afficherImageP }
ajouterImageProduit:
    path:     /imageAjoutFP
    defaults: { _controller: MyappResponsableBundle:Produit:imageAjoutProduitF }
afficherImageProduit:
    path:     /afGI/{id}
    defaults: { _controller: MyappResponsableBundle:Produit:afficherImageProduit }

afficherG:
    path:     /afG/{id}/{catB}
    defaults: { _controller: MyappResponsableBundle:Produit:afficherg }
afficherGC:
    path:     /afGF/{id}/{cat}
    defaults: { _controller: MyappResponsableBundle:Produit:affichergF }
afficherdetailleProduit2 :
    path:     /produit/{id}/{bout}
    defaults: { _controller: MyappResponsableBundle:Produit:afficherPDetaille }
afficher_produit_solde :
    path:     /afficher_produit_solde
    defaults: { _controller: MyappResponsableBundle:Produit:afficher_produit_solde }
afficher_produit_evenement :
    path:     /afficher_produit_evenement
    defaults: { _controller: MyappResponsableBundle:Produit:afficher_produit_evenement }
afficher_produit_new :
    path:     /afficher_produit_new
    defaults: { _controller: MyappResponsableBundle:Produit:afficher_produit_new }


