#services:
##    test_myappresponsable.example:
##        class: test\Myapp\responsableBundle\Example
##        arguments: [@service_id, "plain_value", %parameter%]
services:
  # [...] Vos autres services
  redirect.after.login:
    class: test\Myapp\responsableBundle\Redirection\AfterLoginRedirection
    arguments: [@router]
  redirect.after.logout:
    class:  test\Myapp\responsableBundle\Redirection\AfterLogoutRedirection
    arguments: [@router, @security.context]
  redirect.after.denied :
    class: test\Myapp\responsableBundle\Redirection\AfterDeniedRedirection
    arguments: [@router ,@security.context]

  User.registration.form:
        class:  test\Myapp\responsableBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: user_registration }