services:
     redirect.after.login:
         class: MyApp\adminBundle\Redirection\AfterLoginRedirection
         arguments: [@router]

#  redirect.after.logout:
#    class: Myapp\adminBundle\Redirection\AfterLogoutRedirection
#    arguments: [@router, @security.context]