

#pi2tst_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: testMyappuseBundle:Default:index }
profile_user:
    path:     /
    defaults: { _controller: MyappuserBundle:Accueil:aff }
 

upload_pack: 
    path: /upload 
    defaults: { _controller: MyappuserBundle:Image:upload }
my_app_esprit_list: 
    path: /list 
    defaults: { _controller: MyappuserBundle:Image:list } 
my_app_esprit_aff_article: 
    path: /pack/{id}
    defaults: { _controller: MyappResponsableBundle:Image:affiche } 

catalogue: 
    pattern: /catalogue
    defaults: {_controller: MyappuserBundle:packet:list}     
profile12:
    path:     /profile
    defaults: { _controller: "MyappuserBundle:Profile2:show" }
edit12:
    path:     /edit
    defaults: { _controller: "MyappuserBundle:Profile2:edit" }  

ajouter_Au_panier:
    path:     /ajou
    defaults: { _controller: MyappuserBundle:Panier:ajouter }
tunisia_supprimer_du panier:
    path:     /supp
    defaults: { _controller: MyappuserBundle:Panier:supprimer }
afficher_panier:
    path:     /panier
    defaults: { _controller: MyappuserBundle:Panier:affichage }
afficher_facture:
    path:     /Facture
    defaults: { _controller: MyappuserBundle:Facture:ajouter }    




#
#liraisonf_show:
#    path:     /{id}/show
#    defaults: { _controller: MyappuserBundle:Liraisonf:show }

liraisonf_new:
    path:     /new
    defaults: { _controller: "MyappuserBundle:Liraisonf:new" }

liraisonf_create:
    path:     /create
    defaults: { _controller: "MyappuserBundle:Liraisonf:create" }
 

liraisonf_edit:
    path:     /{id}/edit
    defaults: { _controller: "MyappuserBundle:Liraisonf:edit" }

liraisonf_update:
    path:     /{id}/update
    defaults: { _controller: "MyappuserBundle:Liraisonf:update" }
    requirements: { _method: post|put }

#liraisonf_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "MyappuserBundle:Liraisonf:delete" }
#    requirements: { _method: post|delete }
liraisonf_recherche:
    path:     /recherche
    defaults: { _controller: "MyappuserBundle:Liraisonf:recherche" }
#    requirements: { _method: post|put }
liraisonf_ajout:
    path:     /ajout
    defaults: { _controller: "MyappuserBundle:Liraisonf:ajout" }
    

